In [2]:
import numpy as np


arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print("Original 3x3 Array:")
print(arr)

reshaped_arr = arr.reshape(1,9)

print("Reshaped Array (1x9):")
print(reshaped_arr)


Original 3x3 Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped Array (1x9):
[[1 2 3 4 5 6 7 8 9]]


In [1]:
import numpy as np

a = np.array([10, 20])
b = np.array([2, 3])

result = a * b

print("Array A:", a)
print("Array B:", b)
print("Element-wise Multiplication:", result)


Array A: [10 20]
Array B: [2 3]
Element-wise Multiplication: [20 60]
